# Site Information
title: Ctrl Alt Deploy
description: "Let's platform our way to self-service (without self-desctruction)."
url: https://e-choness.github.io/ctrl-alt-deploy/
repo: e-choness/ctrl-alt-deploy
lang: en-CA
timezone: America/Denver

# Social Media and External URLs
github: e-choness
twitter: _echo_yin
menu:
  - title: "Categories"
    url: "/categories.html"
  - title: "About"
    url: "/about.html"
  - title: "My Profile"
    url: "https://e-choness.github.io/portfolio-site/"

# SEO and Analytics
google_analytics: G-966E405NES

# Build Settings
paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
future: true
highlighter: rouge
markdown: kramdown
permalink: /:year-:month-:day/:title.html
sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:year-:month-:day/:title.html
  posts_en:
    output: true
    permalink: /en/:year-:month-:day/:title.html
    sort_by: date

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-sitemap

# Custom Site Settings
showBuyCoffee: true
payImage: //gw.alipayobjects.com/zos/k/vb/1.png
assetUrl: //tw93.fun/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
